In [ ]:
from google.colab import files
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
!pip install gitpython
import git

# Replace <username> and <token> with your Github username and Personal Access Token
username = "Rajath-k"
token = "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"

# Clone your private repository
git.Repo.clone_from(f"https://{username}:{token}@github.com/<username>/<repository>.git", "/content/<repository>")

GitCommandError: ignored

In [ ]:
uploaded=files.upload()


Saving ua.base to ua.base


In [ ]:
uploaded=files.upload()

Saving ua.test to ua.test


In [ ]:
r_cols=['user_id','movie_id','rating','unix_timestamp']
ratings_train=pd.read_csv("ua.base",sep='\t',names=r_cols,encoding='latin-1')
ratings_test=pd.read_csv("ua.test",sep='\t',names=r_cols,encoding='latin-1')

In [ ]:
ratings_train.shape,ratings_test.shape

((90570, 4), (9430, 4))

In [ ]:
 class MF():
    def __init__(self, R, K, alpha, beta, iterations):
        self.R = R
        self.num_users, self.num_items = R.shape
        self.K = K
        self.alpha = alpha
        self.beta = beta
        self.iterations = iterations



    def train(self):
        self.P = np.random.normal(scale=1./self.K, size=(self.num_users, self.K))
        self.Q = np.random.normal(scale=1./self.K, size=(self.num_items, self.K))


        self.b_u = np.zeros(self.num_users)
        self.b_i = np.zeros(self.num_items)
        self.b = np.mean(self.R[np.where(self.R != 0)])


        self.samples = [
        (i, j, self.R[i, j])
        for i in range(self.num_users)
        for j in range(self.num_items)
        if self.R[i, j] > 0
        ]


        training_process = []
        for i in range(self.iterations):
            np.random.shuffle(self.samples)
            self.sgd()
            mse = self.mse()
            training_process.append((i, mse))
            if (i+1) % 20 == 0:
                print("Iteration: %d ; error = %.4f" % (i+1, mse))

            return training_process


    def mse(self):
        xs, ys = self.R.nonzero()
        predicted = self.full_matrix()
        error = 0
        for x, y in zip(xs, ys):
            error += pow(self.R[x, y] - predicted[x, y], 2)
        return np.sqrt(error)


    def sgd(self):
        for i, j, r in self.samples:
            prediction = self.get_rating(i, j)
            e = (r - prediction)

            self.b_u[i] += self.alpha * (e - self.beta * self.b_u[i])
            self.b_i[j] += self.alpha * (e - self.beta * self.b_i[j])

            self.P[i, :] += self.alpha * (e * self.Q[j, :] - self.beta * self.P[i,:])
            self.Q[j, :] += self.alpha * (e * self.P[i, :] - self.beta * self.Q[j,:])


    def get_rating(self, i, j):
        prediction = self.b + self.b_u[i] + self.b_i[j] + self.P[i, :].dot(self.Q[j, :].T)
        return prediction


    def full_matrix(self):
        return mf.b + mf.b_u[:,np.newaxis] + mf.b_i[np.newaxis:,] + mf.P.dot(mf.Q.T)



In [ ]:
R= np.array(ratings_train.pivot(index = 'user_id', columns ='movie_id', values = 'rating').fillna(0))

In [ ]:
mf = MF(R, K=20, alpha=0.001, beta=0.01, iterations=100)
training_process = mf.train()
print()
print("P x Q:")
mfx=mf.full_matrix()
print(mfx)
print()



P x Q:
[[3.64617472 3.49668908 3.48551385 ... 3.53176389 3.53603606 3.55145621]
 [3.64968818 3.51806859 3.48263565 ... 3.55063353 3.52698215 3.52239564]
 [3.61702397 3.47811023 3.47456631 ... 3.50221993 3.50169638 3.49612559]
 ...
 [3.66207558 3.48671332 3.4951278  ... 3.50965013 3.51652329 3.5254517 ]
 [3.70800799 3.54592825 3.53454318 ... 3.57341147 3.5752385  3.57217001]
 [3.61785425 3.47217947 3.45848565 ... 3.495847   3.48952268 3.51456463]]



In [ ]:

mfx=pd.DataFrame(mfx)
mfx.head()

0         1         2         3         4         5         6     \
0  3.646175  3.496689  3.485514  3.553818  3.549589  3.533173  3.625068   
1  3.649688  3.518069  3.482636  3.554338  3.504518  3.545606  3.608526   
2  3.617024  3.478110  3.474566  3.491945  3.473900  3.504014  3.564516   
3  3.658181  3.491594  3.499143  3.545297  3.526422  3.545967  3.624408   
4  3.558621  3.399761  3.400700  3.437419  3.396536  3.410437  3.509954   

       7         8         9     ...      1670      1671      1672      1673  \
0  3.612797  3.650077  3.556889  ...  3.540614  3.536991  3.562308  3.526243   
1  3.615820  3.608013  3.558130  ...  3.533212  3.530056  3.509544  3.528458   
2  3.592746  3.568099  3.525480  ...  3.495699  3.501572  3.481444  3.495469   
3  3.589896  3.614050  3.564918  ...  3.552442  3.519770  3.531199  3.536964   
4  3.532014  3.510658  3.449537  ...  3.454773  3.413824  3.426045  3.432411   

       1674      1675      1676      1677      1678      1679  
0  3.540550  3.542065  3.541255  3.531764  3.536036  3.551456  
1  3.512125  3.539434  3.543585  3.550634  3.526982  3.522396  
2  3.491158  3.500727  3.504125  3.502220  3.501696  3.496126  
3  3.533424  3.527060  3.541324  3.509836  3.532210  3.537575  
4  3.436292  3.429647  3.428668  3.431954  3.441465  3.430979  

[5 rows x 1680 columns]